name: deploy-auth

on:
  push:
    branches: [ "master" ]
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cd auth && docker build -t juliuss97/auth .
    - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: $ ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: $ ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push juliuss97/auth
    
