name: deploy-auth

on:
  push:
    branches: [ "master" ]
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v3        
    - run: echo $DOCKER_USERNAME
    - run: cd auth && docker build -t $DOCKER_USERNAME/auth .
    - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - run: docker push $DOCKER_USERNAME/auth
    
