name: deploy-tickets

on:
  push:
    branches: [ "master" ]
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKER_ENV
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v3        
    - run: echo $DOCKER_USERNAME
    - run: cd tickets && docker build -t $DOCKER_USERNAME/tickets .
    - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - run: docker push $DOCKER_USERNAME/tickets
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - run: doctl kubernetes cluster kubeconfig save ticketing
    - run: kubectl rollout restart deployment tickets-depl